import type { TestAccount } from "../../../assets/js/types/core";
export declare const TEST_ACCOUNTS: TestAccount[];
export declare const PRIMARY_TEST_LOGIN_EMAIL: string;
export declare const ADMIN_TEST_EMAIL: string;
export declare const AUTH_STORAGE_KEY = "ceeja_portal_auth";
export declare const ADMIN_SESSION_KEY = "ceeja_admin_auth";
export declare const ADMIN_REMEMBER_KEY = "ceeja_admin_auth_remembered";
export declare const SITE_CONTENT_STORAGE_KEY = "ceeja_site_content_draft";
export declare function getPortalSessionEmail(): string | null;
export declare function getRememberedPortalEmail(): string | null;
export declare function syncRememberedPortalSession(): string | null;
export declare function rememberPortal(email: string): void;
export declare function forgetPortal(): void;
export declare function setPortalSession(email: string): void;
export declare function clearPortalAuth(): void;
export declare function getAdminSessionEmail(): string | null;
export declare function getRememberedAdminEmail(): string | null;
export declare function syncRememberedAdminSession(): string | null;
export declare function setAdminSession(email: string): void;
export declare function rememberAdmin(email: string): void;
export declare function forgetAdmin(): void;
export declare function clearAdminAuth(): void;
export declare function isValidTestCredential(email: string, password: string): boolean;
export declare function isAllowedTestUser(email: string): boolean;
export declare function isAllowedAdminUser(email: string): boolean;
