import type { PortalImageLibraryEntry, SiteContent } from "../../../assets/js/types/core";
export declare const SITE_CONTENT_SOURCE = "data/site-content.json";
export declare const PORTAL_IMAGE_UPLOAD_DIR = "assets/images/portal";
export declare function normalizeSiteContent(raw?: Partial<SiteContent> | null): SiteContent;
export declare function readDraftSiteContent(): SiteContent | null;
export declare function saveDraftSiteContent(content: Partial<SiteContent> | SiteContent): void;
export declare function clearDraftSiteContent(): void;
export declare function fetchPublishedSiteContentFromJson(): Promise<SiteContent>;
export declare function fetchPublishedSiteContent(): Promise<SiteContent>;
export declare function loadEditorSiteContent(): Promise<SiteContent>;
export declare function isAllowedPortalImageFileName(fileName?: string): boolean;
export declare function normalizePortalImageLibraryEntries(entries?: Partial<PortalImageLibraryEntry>[] | null): PortalImageLibraryEntry[];
export declare function createPortalImagePath(title: string, originalFileName: string): string;
